name: Scheduled API Calls

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  callApi:
    runs-on: ubuntu-latest

    steps:
      - name: Call API Endpoint
        run: |
          curl -X HEAD https://newsapi-msrnow.vercel.app/api/scrape/trigger-all?github-action-5m
