name: Scheduled API Calls

# Controls when the workflow will run
on:

push:

branches: [ main ]
  pull_request:
    
branches: [ main ]
  # Schedules the workflow to run every 5 minutes
  schedule:
    - cron: '*/5 * * * *'
  
jobs:
  callApi:
    runs-on: ubuntu-latest

    steps:
      - name: Call API Endpoint
        run: |
          curl-I https://newsapi-msrnow.vercel.app/api/scrape/trigger-all?github-action-5m
           if [[ $? -eq 0 ]]; then
            echo "API call was successful"
          else
            echo "API call failed"
            exit 1
          fi
